version: '3.7'
services:
    db2:
      image: ibmcom/db2:11.5.8.0
      container_name: db2
      privileged: true
      ports:
      - "50000:50000"
      environment:
      - DB2INST1_PASSWORD=password
      - LICENSE=accept
      - DBNAME=sample
    iris:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      environment:
        - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      ports:
        - 1972:1972
        - 52773
        - 53773
      volumes:
        - ./:/home/irisowner/dev
